import React, { useEffect } from 'react';
import './ExpertisePage.css';

function ExpertisePage({ setCurrentPage }) {
  useEffect(() => {
    window.scrollTo({ top: 0 });

    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) entry.target.classList.add('visible');
        });
      },
      { threshold: 0.1, rootMargin: '0px 0px -100px 0px' }
    );

    document.querySelectorAll('.fade-in').forEach((el) => observer.observe(el));
    return () => observer.disconnect();
  }, []);

  const handleNav = (e, page) => {
    e.preventDefault();
    setCurrentPage(page);
  };

  const handleSmoothScroll = (e, targetId) => {
    e.preventDefault();
    const target = document.querySelector(targetId);
    if (target) target.scrollIntoView({ behavior: 'smooth', block: 'start' });
  };

  const expertiseAreas = [
    {
      number: '01',
      tag: 'DETECTION',
      title: 'AI-Assisted PPE Detection',
      description:
        'WearAware uses a YOLO-based computer vision model to scan workers at entrance checkpoints and identify whether required PPE — such as helmets and safety vests — is being worn before they enter the worksite.',
      bullets: [
        'Detects helmets and safety vests at checkpoint entry points',
        'Captures a photo as evidence when a violation is flagged',
        'Powered by YOLO for fast on-device inference',
        'Works within the inspector\'s scanning workflow — not a background feed',
      ],
      icon: '🤖',
    },
    {
      number: '02',
      tag: 'IDENTIFICATION',
      title: 'QR-Based Worker Identification',
      description:
        'Each registered worker is assigned a unique QR code tied to their profile. Inspectors scan this code at the checkpoint to link detections directly to a specific worker, making compliance records accurate and traceable.',
      bullets: [
        'Every worker gets a unique QR code generated by the system',
        'QR codes can be printed individually or in bulk from the admin panel',
        'Scans are linked to worker name, employee ID, and assigned station',
        'Supports ZXing and jsQR for browser-based scanning',
      ],
      icon: '🪪',
    },
    {
      number: '03',
      tag: 'LOGGING',
      title: 'Violation & Compliance Logging',
      description:
        'Every scan at a checkpoint is automatically recorded — whether compliant or a violation. Each log entry captures the worker, inspector, station, date, time, detected PPE, and any missing items.',
      bullets: [
        'Logs every scan with full context: worker, inspector, station, timestamp',
        'Flags missing PPE and stores a violation photo as evidence',
        'Filterable detection log by station, inspector, date, and status',
        'Records are stored in PostgreSQL for reliable long-term access',
      ],
      icon: '📋',
    },
    {
      number: '04',
      tag: 'DASHBOARDS',
      title: 'Inspector & Admin Dashboards',
      description:
        'WearAware provides separate role-based interfaces for inspectors and administrators. Inspectors manage their own checkpoint scans, while admins have full visibility across all stations, inspectors, and workers.',
      bullets: [
        'Inspectors see their own scan history, station, and compliance rate',
        'Admins view cross-station detection logs and compliance trends',
        'Overview stats: total scans, violations, compliant scans, compliance rate',
        'Activity log tracks user registrations and checkpoint events',
      ],
      icon: '📊',
    },
    {
      number: '05',
      tag: 'REPORTING',
      title: 'PDF Compliance Reports',
      description:
        'Admins can generate printable PDF compliance reports filtered by time period. Reports include an overall summary, a breakdown by inspector, and a full detection log — ready for review or documentation.',
      bullets: [
        'Filter by today, this week, this month, or a custom date range',
        'Summary section with total scans, violations, and compliance rate',
        'Per-inspector breakdown showing individual performance',
        'Full detection log with worker ID, station, and missing PPE details',
      ],
      icon: '📄',
    },
    {
      number: '06',
      tag: 'ADMINISTRATION',
      title: 'User & Station Management',
      description:
        'Admins have full control over the system — managing inspector accounts, registering workers, configuring checkpoint stations, and handling account requests. Everything is organized from a single admin panel.',
      bullets: [
        'Create, deactivate, or delete inspector and admin accounts',
        'Register workers with assigned stations, positions, and contact info',
        'Configure stations with required PPE and assigned inspectors',
        'Handle password reset requests from inspectors through the admin panel',
      ],
      icon: '⚙️',
    },
  ];

  return (
    <div className="expertise-page">
      {/* Navigation */}
      <nav className="navbar">
        <div className="logo" onClick={(e) => handleNav(e, 'landing')} style={{ cursor: 'pointer' }}>
          <div className="logo-icon">
            <img src="/favicon.svg" alt="WearAware logo" style={{ width: 32, height: 32 }} />
          </div>
          <span>WearAware</span>
        </div>
        <ul className="nav-links">
          <li><a href="#" onClick={(e) => handleNav(e, 'about')}>ABOUT US</a></li>
          <li><a href="#" onClick={(e) => handleNav(e, 'projects')}>OUR PROJECTS</a></li>
          <li><a href="#" onClick={(e) => handleNav(e, 'expertise')}>EXPERTISE</a></li>
          <li><a href="#" onClick={(e) => handleNav(e, 'contact')}>GET IN TOUCH</a></li>
        </ul>
      </nav>

      {/* Hero */}
      <section className="ep-hero">
        <div className="ep-hero-overlay" />
        <div className="ep-hero-content">
          <div className="hero-subtitle">WHAT OUR SYSTEM PROVIDES</div>
          <h1 className="hero-title">OUR AREAS<br />OF EXPERTISE</h1>
          <p className="hero-description">
            Six core capabilities that make up the WearAware PPE compliance system —
            from entrance checkpoint detection to admin-level reporting.
          </p>
          <div className="hero-buttons">
            <a href="#" className="btn btn-primary" onClick={(e) => handleNav(e, 'login')}>GET STARTED</a>
            <a href="#ep-areas" className="btn btn-secondary" onClick={(e) => handleSmoothScroll(e, '#ep-areas')}>EXPLORE</a>
          </div>
        </div>
      </section>

      {/* Intro blurb */}
      <section className="ep-intro fade-in">
        <div className="section-header" style={{ marginBottom: 0 }}>
          <div className="section-subtitle">OUR CAPABILITIES</div>
          <h2 className="section-title">Built for Checkpoint-Based Safety</h2>
          <p className="section-description">
            WearAware is designed around a focused workflow — scan workers at the entrance,
            log compliance, and give admins and inspectors the tools to manage it all.
          </p>
        </div>
      </section>

      {/* Expertise Sections */}
      <main id="ep-areas">
        {expertiseAreas.map((area, i) => (
          <ExpertiseSection key={i} {...area} index={i} />
        ))}
      </main>

      {/* CTA */}
      <section className="cta fade-in" id="ep-contact">
        <h2 className="cta-title">Ready to Set Up WearAware at Your Checkpoint?</h2>
        <p className="cta-description">
          Get started with the system — register your inspectors, configure your stations, and begin logging PPE compliance at your entrance points.
        </p>
        <a href="#" className="btn btn-primary" onClick={(e) => handleNav(e, 'login')}>Get Started Today</a>
      </section>

      {/* Footer */}
      <footer className="footer">
        <div className="footer-simple">
          <div className="footer-brand">
            <img src="/favicon.svg" alt="WearAware logo" style={{ width: 24, height: 24, verticalAlign: 'middle', marginRight: '0.4rem' }} />
            WearAware
          </div>
          <p className="footer-description">
            A Capstone Project by Group 4 - BSIT 2-07
          </p>
          <div className="footer-bottom">
            © 2026 WearAware. All rights reserved. | Built by Group 4 - BSIT2-07
          </div>
        </div>
      </footer>
    </div>
  );
}

function ExpertiseSection({ number, tag, title, description, bullets, icon, index }) {
  const isEven = index % 2 === 0;
  return (
    <section className={`ep-section fade-in ${isEven ? 'ep-section--white' : 'ep-section--gray'}`}>
      <div className="ep-section-inner">
        <div className="ep-section-left">
          <div className="ep-number">{number}</div>
          <div className="ep-tag">{tag}</div>
          <div className="ep-icon-wrap">
            <span className="ep-icon">{icon}</span>
          </div>
          <h2 className="ep-section-title">{title}</h2>
          <div className="ep-accent-bar" />
        </div>

        <div className="ep-section-right">
          <p className="ep-section-desc">{description}</p>
          <ul className="ep-bullets">
            {bullets.map((b, i) => (
              <li key={i} className="ep-bullet">
                <span className="ep-bullet-dot" />
                <span>{b}</span>
              </li>
            ))}
          </ul>
        </div>
      </div>
    </section>
  );
}

export default ExpertisePage;